services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp-NAMAPROJECT
    restart: always
    # ==== PERLU DIGANTI ====
    mem_limit: 384m
    environment:
      WORDPRESS_DB_HOST: db_NAMAPROJECT:3306
      WORDPRESS_DB_USER: "db_user"
      WORDPRESS_DB_PASSWORD: "db_pass"
      WORDPRESS_DB_NAME: "db_nama_db"
      # Opsional: atur upload max size
      PHP_UPLOAD_MAX_FILESIZE: 256M
      PHP_POST_MAX_SIZE: 128M

    # ==== END PERLU DIGANTI ====
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      # ==== PERLU DIGANTI ====
      - "traefik.http.routers.wordpress.rule=Host(`NAMAPROJECT.hafizhsp.id`)"
      # ==== END PERLU DIGANTI ====
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"
      - "traefik.docker.network=edge"

  db_NAMAPROJECT:
    image: mysql:8
    container_name: db-NAMAPROJECT
    restart: always
    # ==== PERLU DIGANTI ====
    mem_limit: 512m
    environment:
      MYSQL_ROOT_PASSWORD: "db_root_pass"
      MYSQL_DATABASE: "db_nama_db"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_pass"
    # ==== END PERLU DIGANTI ====
    volumes:
      - ./mysql_NAMAPROJECT:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/zz-tuning.cnf:ro
    networks:
      - edge

networks:
  edge:
    external: true
